pipeline:
  deploy:
    image: ibmclouddevops/drone-bluemix-cloudfoundry
    region: eu-gb
    org: jcantosz@us.ibm.com
    space: dev
    user: ${USER}
    password: ${PASSWORD}
    domain: eu-gb.mybluemix.net
 
